# Generated by Django 4.1.7 on 2023-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('apodo', models.TextField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_caption_title', models.CharField(max_length=50)),
                ('carousel_caption_description', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
